name: CI

on: [ push, pull_request ]

jobs:

  unit:
    name: "Unit tests"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install
        run: composer install --no-scripts

      - name: Tests - Unit
        run: ./bin/phpunit --testsuite unit

  lint:
    name: "Linter"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install
        run: composer install --no-scripts

      - name: Tests - CS Fixer
        run: ./bin/php-cs-fixer fix --dry-run -vv

  phpstan:
    name: "PHPStan"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpstan

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install
        run: composer install --no-scripts --ignore-platform-req=php

      - name: PHPStan
        run: phpstan analyse

  functional:
    name: "Functional tests"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Copy env file
        run: cp .env.dist .env

      - name: Build Docker images
        uses: docker/bake-action@v6
        with:
          pull: false
          load: false
          files: |
            compose.yml
          set: |
            dbtest.cache-from=type=gha,scope=dbtest-${{ hashFiles('./docker/**') }}
            dbtest.cache-to=type=gha,scope=dbtest-${{ hashFiles('./docker/**') }},mode=max
            apachephp.cache-from=type=gha,scope=apachephp-${{ hashFiles('./docker/**') }}
            apachephp.cache-to=type=gha,scope=apachephp-${{ hashFiles('./docker/**') }},mode=max

      - name: Delete symfony cache
        run: rm -rf var/cache/test

      - name: Tests - Functional
        run: make test-functional

      - uses: actions/upload-artifact@v4
        with:
          name: Functional tests - deprecated log - full
          path: var/logs/test.deprecations.log

      - uses: actions/upload-artifact@v4
        with:
          name: Functional tests - deprecated log - report
          path: var/logs/test.deprecations_grouped.log

      - uses: actions/upload-artifact@v4
        if: failure()
        continue-on-error: true
        with:
          name: Functional tests - log - report
          path: var/logs/test.log

  integration:
    name: "Integration tests"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Copy env file
        run: cp .env.dist .env

      - name: Build Docker images
        uses: docker/bake-action@v6
        with:
          pull: true
          load: true
          files: |
            compose.yml
          set: |
            dbtest.cache-from=type=gha,scope=dbtest-${{ hashFiles('./docker/**') }}
            dbtest.cache-to=type=gha,scope=dbtest-${{ hashFiles('./docker/**') }},mode=max
            apachephp.cache-from=type=gha,scope=apachephp-${{ hashFiles('./docker/**') }}
            apachephp.cache-to=type=gha,scope=apachephp-${{ hashFiles('./docker/**') }},mode=max

      - name: Delete symfony cache
        run: rm -rf var/cache/test

      - name: Tests - Integration
        run: make test-integration-ci
